select set_config(
  'app.sample_opportunity_base_url',
  coalesce(
    nullif(current_setting('app.sample_opportunity_base_url', true), ''),
    'http://localhost:3000/sample-opportunities'
  ),
  false
);

insert into public.opportunities (
  id,
  external_id,
  title,
  organization,
  category,
  location,
  remote_status,
  deadline,
  source_url,
  apply_url,
  description,
  skills,
  eligibility,
  salary_prize_amount,
  status,
  expires_at
)
values
  (
    '11111111-1111-4111-8111-111111111111',
    'sample-frontend-developer-internship',
    'Frontend Developer Internship',
    'Northstar Labs',
    'internship',
    'United States',
    'hybrid',
    now() + interval '45 days',
    current_setting('app.sample_opportunity_base_url') || '/frontend-developer-internship',
    current_setting('app.sample_opportunity_base_url') || '/frontend-developer-internship/apply',
    'Work with a product engineering team to build accessible web interfaces, ship React features, and learn production frontend workflows.',
    array['React', 'TypeScript', 'UI/UX', 'Next.js'],
    '{"experience": "Beginner friendly", "requirements": ["Portfolio or GitHub samples", "Comfortable with JavaScript fundamentals"]}'::jsonb,
    '$1,500 monthly stipend',
    'published',
    now() + interval '45 days'
  ),
  (
    '77777777-7777-4777-8777-777777777777',
    'sample-backend-developer',
    'Backend Developer',
    'Atlas API Studio',
    'job',
    'Canada',
    'remote',
    now() + interval '50 days',
    current_setting('app.sample_opportunity_base_url') || '/backend-developer',
    current_setting('app.sample_opportunity_base_url') || '/backend-developer/apply',
    'Build reliable API services, background jobs, and PostgreSQL-backed workflows for a fast-growing opportunity platform.',
    array['Node.js', 'TypeScript', 'PostgreSQL', 'API Design'],
    '{"experience": "Intermediate", "requirements": ["REST API experience", "Database schema design", "Testing discipline"]}'::jsonb,
    '$95,000 salary',
    'published',
    now() + interval '50 days'
  ),
  (
    '88888888-8888-4888-8888-888888888888',
    'sample-solidity-developer',
    'Solidity Developer',
    'ChainForge DAO',
    'job',
    'Global',
    'remote',
    now() + interval '35 days',
    current_setting('app.sample_opportunity_base_url') || '/solidity-developer',
    current_setting('app.sample_opportunity_base_url') || '/solidity-developer/apply',
    'Implement and audit smart contract features for grants, rewards, and on-chain application workflows.',
    array['Solidity', 'Smart Contracts', 'Foundry', 'TypeScript'],
    '{"experience": "Intermediate to advanced", "requirements": ["Smart contract portfolio", "Security-aware development", "Testnet deployment experience"]}'::jsonb,
    '$8,000 project reward',
    'published',
    now() + interval '35 days'
  ),
  (
    '99999999-9999-4999-8999-999999999999',
    'sample-ai-engineer',
    'AI Engineer',
    'SignalWorks AI',
    'job',
    'United Kingdom',
    'hybrid',
    now() + interval '42 days',
    current_setting('app.sample_opportunity_base_url') || '/ai-engineer',
    current_setting('app.sample_opportunity_base_url') || '/ai-engineer/apply',
    'Design retrieval, evaluation, and prompt workflows that turn messy opportunity data into useful recommendations.',
    array['Python', 'LLMs', 'Machine Learning', 'PostgreSQL'],
    '{"experience": "Mid-level", "requirements": ["Python production experience", "LLM or retrieval project", "Comfort with evaluation metrics"]}'::jsonb,
    '$120,000 salary',
    'published',
    now() + interval '42 days'
  ),
  (
    'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    'sample-frontend-developer',
    'Frontend Developer',
    'PixelFoundry',
    'job',
    'Nigeria',
    'remote',
    now() + interval '28 days',
    current_setting('app.sample_opportunity_base_url') || '/frontend-developer',
    current_setting('app.sample_opportunity_base_url') || '/frontend-developer/apply',
    'Create polished, responsive interfaces for opportunity search, saved lists, and AI-assisted application workflows.',
    array['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    '{"experience": "Junior to mid-level", "requirements": ["Responsive UI examples", "React state management", "Accessibility basics"]}'::jsonb,
    '$70,000 salary',
    'published',
    now() + interval '28 days'
  ),
  (
    '22222222-2222-4222-8222-222222222222',
    'sample-react-open-source-bounty',
    'React Open Source Bounty',
    'Open Components Collective',
    'bounty',
    'Global',
    'remote',
    now() + interval '21 days',
    current_setting('app.sample_opportunity_base_url') || '/react-open-source-bounty',
    current_setting('app.sample_opportunity_base_url') || '/react-open-source-bounty/apply',
    'Fix component bugs, improve test coverage, and document reusable React primitives in an active open source repository.',
    array['React', 'TypeScript', 'Node.js'],
    '{"experience": "Intermediate", "requirements": ["Prior pull request experience", "Ability to write clear technical notes"]}'::jsonb,
    '$750 bounty',
    'published',
    now() + interval '21 days'
  ),
  (
    '33333333-3333-4333-8333-333333333333',
    'sample-ai-hackathon',
    'AI Hackathon',
    'Builder Circuit',
    'hackathon',
    'Global',
    'remote',
    now() + interval '30 days',
    current_setting('app.sample_opportunity_base_url') || '/ai-hackathon',
    current_setting('app.sample_opportunity_base_url') || '/ai-hackathon/register',
    'Build a prototype that helps people discover, evaluate, or apply to career opportunities using practical AI workflows.',
    array['Python', 'Next.js', 'TypeScript', 'UI/UX'],
    '{"team_size": "1-4", "requirements": ["Working demo", "Short project write-up"]}'::jsonb,
    '$5,000 prize pool',
    'published',
    now() + interval '30 days'
  ),
  (
    '44444444-4444-4444-8444-444444444444',
    'sample-startup-grant',
    'Startup Grant',
    'Launchpad Foundation',
    'grant',
    'Africa',
    'remote',
    now() + interval '60 days',
    current_setting('app.sample_opportunity_base_url') || '/startup-grant',
    current_setting('app.sample_opportunity_base_url') || '/startup-grant/apply',
    'Non-dilutive funding for early builders working on software products for education, work, finance, or developer tooling.',
    array['Product Strategy', 'Node.js', 'Python', 'UI/UX'],
    '{"stage": "Idea to MVP", "requirements": ["Problem statement", "Budget plan", "Founder profile"]}'::jsonb,
    'Up to $10,000 grant',
    'published',
    now() + interval '60 days'
  ),
  (
    '55555555-5555-4555-8555-555555555555',
    'sample-software-engineering-fellowship',
    'Software Engineering Fellowship',
    'Future Code Institute',
    'fellowship',
    'Europe',
    'hybrid',
    now() + interval '75 days',
    current_setting('app.sample_opportunity_base_url') || '/software-engineering-fellowship',
    current_setting('app.sample_opportunity_base_url') || '/software-engineering-fellowship/apply',
    'A six-month fellowship combining mentorship, applied engineering projects, and career support for emerging software engineers.',
    array['TypeScript', 'Node.js', 'Python', 'React'],
    '{"experience": "Beginner to intermediate", "requirements": ["Two project samples", "Availability for weekly sessions"]}'::jsonb,
    'Mentorship and travel support',
    'published',
    now() + interval '75 days'
  ),
  (
    '66666666-6666-4666-8666-666666666666',
    'sample-scholarship-for-developers',
    'Scholarship for Developers',
    'Code Access Fund',
    'scholarship',
    'Global',
    'remote',
    now() + interval '90 days',
    current_setting('app.sample_opportunity_base_url') || '/scholarship-for-developers',
    current_setting('app.sample_opportunity_base_url') || '/scholarship-for-developers/apply',
    'Scholarship support for developers pursuing technical courses, certifications, bootcamps, or project-based learning programs.',
    array['React', 'Python', 'Solidity', 'UI/UX'],
    '{"requirements": ["Learning plan", "Financial need statement", "Recent project or coursework"]}'::jsonb,
    'Up to $2,500 tuition support',
    'published',
    now() + interval '90 days'
  )
on conflict (id) do update
set
  external_id = excluded.external_id,
  title = excluded.title,
  organization = excluded.organization,
  category = excluded.category,
  location = excluded.location,
  remote_status = excluded.remote_status,
  deadline = excluded.deadline,
  source_url = excluded.source_url,
  apply_url = excluded.apply_url,
  description = excluded.description,
  skills = excluded.skills,
  eligibility = excluded.eligibility,
  salary_prize_amount = excluded.salary_prize_amount,
  status = excluded.status,
  expires_at = excluded.expires_at,
  updated_at = now();
